site_name: Compooler Docs
theme: readthedocs
nav:
  - Welcome: index.md
  - Initial design document: initial.md
  - Business:
      - Domain model: business/model.md
  - Technical:
      - Back end:
          - Overview: technical/back_end/overview.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - mdx_truly_sane_lists
