services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Compooler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 3s
      retries: 5