name: API CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/api/**
  pull_request:
    branches:
      - main
    paths:
      - src/api/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/api
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Restore tools
        run: dotnet tool restore
      - name: Check formatting
        run: dotnet csharpier --check .
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
      - name: Generate test report
        uses: bibipkins/dotnet-test-reporter@v1.4.1
        if: success() || failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-path: "src/api/*.Tests/**/*.trx"
          coverage-path: "src/api/*.Tests/**/coverage.cobertura.xml"
          coverage-threshold: 80
          coverage-type: cobertura
